apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "allday-frontend-helm.fullname" . }}
  labels:
    {{- include "allday-frontend-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "allday-frontend-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "allday-frontend-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 2Gi
      
